In [9]:
"""Locate maximum value."""

import numpy as np


def get_max_index(a):
    """Return the index of the maximum value in given 1D array."""
    # TODO: Your code here
    return np.argmax(a) 

def test_run():
    a = np.array([9, 6, 2, 3, 12, 14, 7, 10], dtype=np.int32)  # 32-bit integer array
    print ("Array:", a)
    
    # Find the maximum and its index in array
    print ("Maximum value:", a.max())
    print ("Index of max.:", get_max_index(a))


if __name__ == "__main__":
    test_run()


Array: [ 9  6  2  3 12 14  7 10]
Maximum value: 14
Index of max.: 5


In [11]:
import time

def test_run():
    t1 = time.time()
    print("ML4T")
    t2 = time.time()
    print("The time taken by print statement is ", t2 - t1 ," seconds")
    
    


if __name__ == "__main__":
    test_run()

ML4T
The time taken by print statement is  0.0  seconds


In [15]:
#Accessing array elements
import numpy as np

def test_run():
    a = np.random.rand(5, 4)
    print("Array: \n", a)
    
    #Accessing element at position (3, 2)
    element = a[3, 2]
    
    #Element in defined range
    print(a[0, 1:3])
    
    #Top left corner
    print(a[0:2, 0:2])
    
    #Slice n:m:t specifies a range that starts in n, stops before m of size t
    print(a[:, 0:3:2]) #Will select columns 0, 2 for every row


if __name__ == "__main__":
    test_run()



Array: 
 [[0.15183634 0.71986715 0.03979915 0.66566073]
 [0.68864517 0.68210441 0.12543607 0.59247708]
 [0.19597311 0.94593035 0.05061334 0.21139713]
 [0.85541275 0.91051    0.85468252 0.55898472]
 [0.7423778  0.82598322 0.74542096 0.34694188]]
[0.71986715 0.03979915]
[[0.15183634 0.71986715]
 [0.68864517 0.68210441]]
[[0.15183634 0.03979915]
 [0.68864517 0.12543607]
 [0.19597311 0.05061334]
 [0.85541275 0.85468252]
 [0.7423778  0.74542096]]
